# Generated by Django 6.1 on 2026-10-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0002_remove_productimage_is_primary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=900, max_digits=30),
            preserve_default=False,
        ),
    ]
