# Generated by Django 6.1 on 2026-10-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_line_1',
        ),
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
